name: Firma
version: '${project.version}'
main: ch.andu.firma.Firma
api-version: 1.18
authors: [ anducrafter ]
description: SkySucht Firma Plugin
website: forum.skysucht.com
commands:
  firma:
  auftrag:
